skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
t22 = "JBkN5Y4D3TqaR35s9tQypwLvc9Wq9Prsk9QgKeY9b2BV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
